.ONESHELL:

all:
	fasm cicada-nymph.fasm

clean*~:
	rm -f *~ */*~ */*/*~ */*/*/*~ */*/*/*/*~  */*/*/*/*/*~  

clean:
	make clean*~                                  &&\
	echo -e "\e[33;1m [ok] clean directory \e[0m"
